name: Build latest Docker image and push to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # needed for the history generation

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: create sha tag
        run: |
          TAG=sha-$(echo $GITHUB_SHA | cut -c1-7)
          echo "TAG=$TAG" >> $GITHUB_ENV
          docker buildx create --use

      - name: Build and push multi-arch image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            effex7/luna2calendar:${{ env.TAG }}
            effex7/luna2calendar:latest
          platforms: linux/amd64,linux/arm64
